#DBをMySQLに統一（２０１９・６・５）
#   記載を変更（２０１９・６・６）

development: &development
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: shop_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: shop_test
  pool: 5
  username: root
  password: 


production: &production
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: shop_production
  pool: 40
  username: shop
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>