#DBをMySQLに統一（２０１９・６・５）
#   記載を変更（２０１９・６・６）

development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_development
  pool: 5
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
  #socketを”/tmp/mysql.sock”から”/var/lib/mysql/mysql.sock”に変更（mysql_config --socketで調べた結果　２０１９・６・９）

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_test
  pool: 5
  username: root
  password: 


production: &production
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_production
  pool: 40
  username: shop
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>